name: Update ICS

on:
  schedule:
    - cron: '0 15 * * 1'  # 每周触发
  workflow_dispatch:      # 可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ics pytz

      - name: Run Python script
        run: python plavecalendar.py

      - name: Commit and push ICS
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add plave.ics
          git commit -m "Update ICS [ci skip]" || echo "No changes"
          git push
